apiVersion: apps/v1
kind: Deployment
metadata:
  name: jensenstore-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jensenstore-api
  template:
    metadata:
      labels:
        app: jensenstore-api
    spec:
      containers:
        - name: api
          image: jensenstore-api:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v2"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
